# Generated by Django 3.1.7 on 2021-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
