# Generated by Django 3.1.7 on 2021-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210325_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
